### ISSUE TITLE
policy for duplicate handling

### ISSUE THREAD

**Issue by ltalirz** [danieleongari/CURATED-COFs#12]
@danieleongari What is the policy when duplicates are detected - should they simply be kept in the database?

If yes, I think the "Duplicate found" column should always go both ways - e.g. the entry for 09000N3 should indicate duplicate 18132N3, just as the entry for 18132N3 indicates duplicate 18132N3 (also this would be easy to check automatically).

Further possible duplicates based on the trivial name (some potentially already caught):
```
['cof 1', 'cof 300', 't cof 1', 't cof 2', 'cof sdu1', 'ph an cof', 'n3 cof', 'por cof', 'tpb2 cof', 'py cof', 'red pv cof']
```

**Comment by ltalirz** [comment]
For example, red pv COF is suggested as the name of the COF in https://pubs.acs.org/doi/10.1021/acsami.9b17324 but I don't see this name in the abstract
For the article with the Red-pv-cof https://pubs.rsc.org/en/content/articlelanding/2020/SC/C9SC04663A#!divAbstract, other pv-cofs mentioned there are not listed (perhaps they were duplicates?)

**Comment by danieleongari** [comment]
There is not an unique way to proceed with this:
- as for the duplicate "COF-1" we know that there is another COFs called (without much fantasy) like that. We could opt for changing it somehow to make the names uniques (e.g., COF-1-authorname)
- as for the duplicates, we can list them and drop them, as there is no point to keep both, unless they are like AA, AB. Intermediate configurations may need non-obvious decisions. 
- 19560N2 should be named as DhaTab-V instead of Red-PV-COF (I have no clue how this could be named in such a way) 

Since we will continue to find these little errors, and they needs to be corrected in all the databases (Git, AiiDA/discovery, AiiDA MatScreen, AiiDA/mycomputer) I suggest to postpone the correction to the next update, and keep opening issues for them.

**Comment by ltalirz** [comment]
@danieleongari I guess by including the author name in the trivial name, this one can be considered fixed(?)

For the Red-PV-COF did you fix the name?

**Comment by danieleongari** [comment]
Yes, this has been fixed in https://github.com/danieleongari/CURATED-COFs/pull/22
