### ISSUE TITLE
`.csv` of simulated adsorption properties

### ISSUE THREAD

**Issue by SimonEnsemble** [danieleongari/CURATED-COFs#17]
cool paper @danieleongari and @ltalirz!

do you have a table (`.csv`) of the simulated adsorption properties [here](https://aiida-dev.materialscloud.org/curated-cofs/discover/results) somewhere?

thanks!
CC @Surluson.

**Comment by danieleongari** [comment]
Thanks Cory, 
at the moment we don't provide a csv file because there are too many properties that we can print on it:
the main interface shows only two parameters per applications, but we have also all the data for the isotherms (it becomes complex to make a csv with pressure points that are numerically different because generated depending on the steepness of the kH), geometric properties, post processing, etc. 
Therefore, it makes more sense to download and import the AiiDA database (see the associated Materials Cloud Archive [page](https://archive.materialscloud.org/record/2020.107) we provide and use the [advanced querying system](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/database.html?highlight=querybuilder) built in AiiDA to retrieve the needed values.

However, if you think that, for your user case, just the numerical values for the scattered plots we showed are enough, we will consider making a static csv with these values to download.

**Comment by Surluson** [comment]
Thanks for the help @danieleongari !
I was able to retrieve the information I was interested in by querying the database.
The easiest way I was able to do this was querying based on `Groups` and using the `extras.tag4` tags to grab the relevant info.
I wasn't able to find info on the `Groups` (sorry if there is, I didn't do an exhaustive search), so maybe it's worth it to include a small description on the groups and how to use them to query.

**Comment by danieleongari** [comment]
Great! You are right, there are some info about the database structure here in the repository of the visualization program (https://github.com/lsmo-epfl/discover-curated-cofs) but the README was not fully updated with the new API because we still need to make some choices about it. With the October-2020 update on materials cloud we will specify better the database structure.
